CREATE TABLE sys_user
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(64)              NOT NULL,
    display_name  varchar(64)              NOT NULL,
    password_hash varchar(255)             NOT NULL,
    enabled       boolean                  NOT NULL DEFAULT true,
    created_at    timestamp with time zone NOT NULL DEFAULT current_timestamp,
    updated_at    timestamp with time zone NOT NULL DEFAULT current_timestamp,
    CONSTRAINT uk_sys_user_username UNIQUE (username)
);

COMMENT ON TABLE sys_user IS '系统用户';
COMMENT ON COLUMN sys_user.password_hash IS '密码哈希，不存储明文密码';
