spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DATABASE}
      password: ${REDIS_PASSWORD}
      connect-timeout: 2s
      timeout: 2s
      repositories:
        enabled: false
