server:
  port: 8080

logging:
  level:
    root: info
    com.qboot: debug

spring:
  application:
    name: app-auth
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/qboot}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  flyway:
    enabled: false
    locations: classpath:db/migration
    validate-migration-naming: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
      connect-timeout: 2s
      timeout: 2s
      repositories:
        enabled: false
